// Generated by rstantools.  Do not edit by hand.

/*
    eDNAjoint is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    eDNAjoint is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with eDNAjoint.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_joint_binary_catchability_gamma_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 78> locations_array__ =
  {" (found before start of program)",
  " (in 'joint_binary_catchability_gamma', line 15, column 4 to column 42)",
  " (in 'joint_binary_catchability_gamma', line 16, column 4 to column 45)",
  " (in 'joint_binary_catchability_gamma', line 17, column 4 to column 14)",
  " (in 'joint_binary_catchability_gamma', line 18, column 4 to column 26)",
  " (in 'joint_binary_catchability_gamma', line 19, column 4 to column 44)",
  " (in 'joint_binary_catchability_gamma', line 22, column 2 to column 43)",
  " (in 'joint_binary_catchability_gamma', line 23, column 2 to column 40)",
  " (in 'joint_binary_catchability_gamma', line 24, column 2 to column 26)",
  " (in 'joint_binary_catchability_gamma', line 25, column 2 to column 33)",
  " (in 'joint_binary_catchability_gamma', line 26, column 2 to column 33)",
  " (in 'joint_binary_catchability_gamma', line 53, column 2 to column 20)",
  " (in 'joint_binary_catchability_gamma', line 54, column 2 to column 22)",
  " (in 'joint_binary_catchability_gamma', line 55, column 2 to column 28)",
  " (in 'joint_binary_catchability_gamma', line 56, column 2 to column 11)",
  " (in 'joint_binary_catchability_gamma', line 28, column 4 to column 43)",
  " (in 'joint_binary_catchability_gamma', line 29, column 4 to column 45)",
  " (in 'joint_binary_catchability_gamma', line 30, column 4 to column 33)",
  " (in 'joint_binary_catchability_gamma', line 27, column 19 to line 31, column 3)",
  " (in 'joint_binary_catchability_gamma', line 27, column 2 to line 31, column 3)",
  " (in 'joint_binary_catchability_gamma', line 33, column 6 to column 48)",
  " (in 'joint_binary_catchability_gamma', line 32, column 15 to line 34, column 5)",
  " (in 'joint_binary_catchability_gamma', line 32, column 2 to line 34, column 5)",
  " (in 'joint_binary_catchability_gamma', line 36, column 6 to column 42)",
  " (in 'joint_binary_catchability_gamma', line 35, column 17 to line 37, column 5)",
  " (in 'joint_binary_catchability_gamma', line 35, column 4 to line 37, column 5)",
  " (in 'joint_binary_catchability_gamma', line 57, column 2 to column 21)",
  " (in 'joint_binary_catchability_gamma', line 58, column 2 to column 18)",
  " (in 'joint_binary_catchability_gamma', line 59, column 2 to column 27)",
  " (in 'joint_binary_catchability_gamma', line 61, column 4 to column 36)",
  " (in 'joint_binary_catchability_gamma', line 60, column 21 to line 62, column 3)",
  " (in 'joint_binary_catchability_gamma', line 60, column 2 to line 62, column 3)",
  " (in 'joint_binary_catchability_gamma', line 64, column 10 to column 92)",
  " (in 'joint_binary_catchability_gamma', line 63, column 17 to line 65, column 7)",
  " (in 'joint_binary_catchability_gamma', line 63, column 4 to line 65, column 7)",
  " (in 'joint_binary_catchability_gamma', line 67, column 10 to column 61)",
  " (in 'joint_binary_catchability_gamma', line 66, column 19 to line 68, column 7)",
  " (in 'joint_binary_catchability_gamma', line 66, column 6 to line 68, column 7)",
  " (in 'joint_binary_catchability_gamma', line 41, column 8 to column 71)",
  " (in 'joint_binary_catchability_gamma', line 40, column 18 to line 42, column 5)",
  " (in 'joint_binary_catchability_gamma', line 40, column 4 to line 42, column 5)",
  " (in 'joint_binary_catchability_gamma', line 44, column 8 to column 39)",
  " (in 'joint_binary_catchability_gamma', line 43, column 18 to line 45, column 5)",
  " (in 'joint_binary_catchability_gamma', line 43, column 4 to line 45, column 5)",
  " (in 'joint_binary_catchability_gamma', line 47, column 2 to column 47)",
  " (in 'joint_binary_catchability_gamma', line 48, column 2 to column 22)",
  " (in 'joint_binary_catchability_gamma', line 49, column 2 to column 32)",
  " (in 'joint_binary_catchability_gamma', line 50, column 2 to column 33)",
  " (in 'joint_binary_catchability_gamma', line 2, column 4 to column 19)",
  " (in 'joint_binary_catchability_gamma', line 3, column 4 to column 19)",
  " (in 'joint_binary_catchability_gamma', line 4, column 10 to column 11)",
  " (in 'joint_binary_catchability_gamma', line 4, column 4 to column 28)",
  " (in 'joint_binary_catchability_gamma', line 5, column 10 to column 11)",
  " (in 'joint_binary_catchability_gamma', line 5, column 4 to column 28)",
  " (in 'joint_binary_catchability_gamma', line 6, column 4 to column 22)",
  " (in 'joint_binary_catchability_gamma', line 7, column 10 to column 11)",
  " (in 'joint_binary_catchability_gamma', line 7, column 4 to column 29)",
  " (in 'joint_binary_catchability_gamma', line 8, column 10 to column 11)",
  " (in 'joint_binary_catchability_gamma', line 8, column 4 to column 28)",
  " (in 'joint_binary_catchability_gamma', line 9, column 10 to column 11)",
  " (in 'joint_binary_catchability_gamma', line 9, column 4 to column 28)",
  " (in 'joint_binary_catchability_gamma', line 10, column 4 to column 28)",
  " (in 'joint_binary_catchability_gamma', line 11, column 4 to column 25)",
  " (in 'joint_binary_catchability_gamma', line 12, column 11 to column 12)",
  " (in 'joint_binary_catchability_gamma', line 12, column 13 to column 20)",
  " (in 'joint_binary_catchability_gamma', line 12, column 4 to column 26)",
  " (in 'joint_binary_catchability_gamma', line 15, column 10 to column 14)",
  " (in 'joint_binary_catchability_gamma', line 16, column 10 to column 14)",
  " (in 'joint_binary_catchability_gamma', line 19, column 27 to column 34)",
  " (in 'joint_binary_catchability_gamma', line 22, column 8 to column 12)",
  " (in 'joint_binary_catchability_gamma', line 23, column 8 to column 12)",
  " (in 'joint_binary_catchability_gamma', line 24, column 18 to column 19)",
  " (in 'joint_binary_catchability_gamma', line 25, column 8 to column 12)",
  " (in 'joint_binary_catchability_gamma', line 26, column 8 to column 9)",
  " (in 'joint_binary_catchability_gamma', line 53, column 9 to column 16)",
  " (in 'joint_binary_catchability_gamma', line 54, column 9 to column 12)",
  " (in 'joint_binary_catchability_gamma', line 55, column 9 to column 13)",
  " (in 'joint_binary_catchability_gamma', line 55, column 14 to column 23)"};
#include <stan_meta_header.hpp>
class model_joint_binary_catchability_gamma final : public model_base_crtp<model_joint_binary_catchability_gamma> {
private:
  int S;
  int C;
  std::vector<int> L;
  std::vector<int> R;
  int Nloc;
  std::vector<double> E;
  std::vector<int> N;
  std::vector<int> K;
  std::vector<double> p10priors;
  int nparams;
  Eigen::Matrix<double,-1,-1> mat_data__;
  int log_lik_1dim__;
  int mu_2dim__;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> mat{nullptr, 0, 0};
public:
  ~model_joint_binary_catchability_gamma() {}
  model_joint_binary_catchability_gamma(stan::io::var_context& context__,
                                        unsigned int random_seed__ = 0,
                                        std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_joint_binary_catchability_gamma_namespace::model_joint_binary_catchability_gamma";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 48;
      context__.validate_dims("data initialization", "S", "int",
        std::vector<size_t>{});
      S = std::numeric_limits<int>::min();
      current_statement__ = 48;
      S = context__.vals_i("S")[(1 - 1)];
      current_statement__ = 48;
      stan::math::check_greater_or_equal(function__, "S", S, 1);
      current_statement__ = 49;
      context__.validate_dims("data initialization", "C", "int",
        std::vector<size_t>{});
      C = std::numeric_limits<int>::min();
      current_statement__ = 49;
      C = context__.vals_i("C")[(1 - 1)];
      current_statement__ = 49;
      stan::math::check_greater_or_equal(function__, "C", C, 1);
      current_statement__ = 50;
      stan::math::validate_non_negative_index("L", "S", S);
      current_statement__ = 51;
      context__.validate_dims("data initialization", "L", "int",
        std::vector<size_t>{static_cast<size_t>(S)});
      L = std::vector<int>(S, std::numeric_limits<int>::min());
      current_statement__ = 51;
      L = context__.vals_i("L");
      current_statement__ = 51;
      stan::math::check_greater_or_equal(function__, "L", L, 1);
      current_statement__ = 52;
      stan::math::validate_non_negative_index("R", "C", C);
      current_statement__ = 53;
      context__.validate_dims("data initialization", "R", "int",
        std::vector<size_t>{static_cast<size_t>(C)});
      R = std::vector<int>(C, std::numeric_limits<int>::min());
      current_statement__ = 53;
      R = context__.vals_i("R");
      current_statement__ = 53;
      stan::math::check_greater_or_equal(function__, "R", R, 1);
      current_statement__ = 54;
      context__.validate_dims("data initialization", "Nloc", "int",
        std::vector<size_t>{});
      Nloc = std::numeric_limits<int>::min();
      current_statement__ = 54;
      Nloc = context__.vals_i("Nloc")[(1 - 1)];
      current_statement__ = 54;
      stan::math::check_greater_or_equal(function__, "Nloc", Nloc, 1);
      current_statement__ = 55;
      stan::math::validate_non_negative_index("E", "C", C);
      current_statement__ = 56;
      context__.validate_dims("data initialization", "E", "double",
        std::vector<size_t>{static_cast<size_t>(C)});
      E = std::vector<double>(C, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 56;
      E = context__.vals_r("E");
      current_statement__ = 56;
      stan::math::check_greater_or_equal(function__, "E", E, 0);
      current_statement__ = 57;
      stan::math::validate_non_negative_index("N", "S", S);
      current_statement__ = 58;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{static_cast<size_t>(S)});
      N = std::vector<int>(S, std::numeric_limits<int>::min());
      current_statement__ = 58;
      N = context__.vals_i("N");
      current_statement__ = 58;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 59;
      stan::math::validate_non_negative_index("K", "S", S);
      current_statement__ = 60;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{static_cast<size_t>(S)});
      K = std::vector<int>(S, std::numeric_limits<int>::min());
      current_statement__ = 60;
      K = context__.vals_i("K");
      current_statement__ = 60;
      stan::math::check_greater_or_equal(function__, "K", K, 0);
      current_statement__ = 61;
      context__.validate_dims("data initialization", "p10priors", "double",
        std::vector<size_t>{static_cast<size_t>(2)});
      p10priors = std::vector<double>(2,
                    std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 61;
      p10priors = context__.vals_r("p10priors");
      current_statement__ = 62;
      context__.validate_dims("data initialization", "nparams", "int",
        std::vector<size_t>{});
      nparams = std::numeric_limits<int>::min();
      current_statement__ = 62;
      nparams = context__.vals_i("nparams")[(1 - 1)];
      current_statement__ = 62;
      stan::math::check_greater_or_equal(function__, "nparams", nparams, 0);
      current_statement__ = 63;
      stan::math::validate_non_negative_index("mat", "C", C);
      current_statement__ = 64;
      stan::math::validate_non_negative_index("mat", "nparams", nparams);
      current_statement__ = 65;
      context__.validate_dims("data initialization", "mat", "double",
        std::vector<size_t>{static_cast<size_t>(C),
          static_cast<size_t>(nparams)});
      mat_data__ = Eigen::Matrix<double,-1,-1>::Constant(C, nparams,
                     std::numeric_limits<double>::quiet_NaN());
      new (&mat) Eigen::Map<Eigen::Matrix<double,-1,-1>>(mat_data__.data(),
        C, nparams);
      {
        std::vector<local_scalar_t__> mat_flat__;
        current_statement__ = 65;
        mat_flat__ = context__.vals_r("mat");
        current_statement__ = 65;
        pos__ = 1;
        current_statement__ = 65;
        for (int sym1__ = 1; sym1__ <= nparams; ++sym1__) {
          current_statement__ = 65;
          for (int sym2__ = 1; sym2__ <= C; ++sym2__) {
            current_statement__ = 65;
            stan::model::assign(mat, mat_flat__[(pos__ - 1)],
              "assigning variable mat", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 65;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 66;
      stan::math::validate_non_negative_index("alpha_gamma", "Nloc", Nloc);
      current_statement__ = 67;
      stan::math::validate_non_negative_index("beta_gamma", "Nloc", Nloc);
      current_statement__ = 68;
      stan::math::validate_non_negative_index("q_trans", "nparams", nparams);
      current_statement__ = 69;
      stan::math::validate_non_negative_index("p11", "Nloc", Nloc);
      current_statement__ = 70;
      stan::math::validate_non_negative_index("p", "Nloc", Nloc);
      current_statement__ = 71;
      stan::math::validate_non_negative_index("coef", "C", C);
      current_statement__ = 72;
      stan::math::validate_non_negative_index("mu_1", "Nloc", Nloc);
      current_statement__ = 73;
      stan::math::validate_non_negative_index("E_trans", "C", C);
      current_statement__ = 74;
      stan::math::validate_non_negative_index("q", "nparams", nparams);
      current_statement__ = 75;
      log_lik_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 75;
      log_lik_1dim__ = (C + S);
      current_statement__ = 75;
      stan::math::validate_non_negative_index("log_lik", "C + S",
        log_lik_1dim__);
      current_statement__ = 76;
      stan::math::validate_non_negative_index("mu", "Nloc", Nloc);
      current_statement__ = 77;
      mu_2dim__ = std::numeric_limits<int>::min();
      current_statement__ = 77;
      mu_2dim__ = (nparams + 1);
      current_statement__ = 77;
      stan::math::validate_non_negative_index("mu", "nparams + 1", mu_2dim__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = Nloc + Nloc + 1 + 1 + nparams;
  }
  inline std::string model_name() const final {
    return "model_joint_binary_catchability_gamma";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_joint_binary_catchability_gamma_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<local_scalar_t__> alpha_gamma =
        std::vector<local_scalar_t__>(Nloc, DUMMY_VAR__);
      current_statement__ = 1;
      alpha_gamma = in__.template read_constrain_lb<
                      std::vector<local_scalar_t__>, jacobian__>(0, lp__,
                      Nloc);
      std::vector<local_scalar_t__> beta_gamma =
        std::vector<local_scalar_t__>(Nloc, DUMMY_VAR__);
      current_statement__ = 2;
      beta_gamma = in__.template read_constrain_lb<
                     std::vector<local_scalar_t__>, jacobian__>(0.01, lp__,
                     Nloc);
      local_scalar_t__ beta = DUMMY_VAR__;
      current_statement__ = 3;
      beta = in__.template read<local_scalar_t__>();
      local_scalar_t__ log_p10 = DUMMY_VAR__;
      current_statement__ = 4;
      log_p10 = in__.template read_constrain_ub<local_scalar_t__,
                  jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> q_trans =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nparams, DUMMY_VAR__);
      current_statement__ = 5;
      q_trans = in__.template read_constrain_lb<
                  Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(-0.99999,
                  lp__, nparams);
      std::vector<local_scalar_t__> p11 =
        std::vector<local_scalar_t__>(Nloc, DUMMY_VAR__);
      std::vector<local_scalar_t__> p =
        std::vector<local_scalar_t__>(Nloc, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> coef =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(C, DUMMY_VAR__);
      std::vector<local_scalar_t__> mu_1 =
        std::vector<local_scalar_t__>(Nloc, DUMMY_VAR__);
      std::vector<local_scalar_t__> E_trans =
        std::vector<local_scalar_t__>(C, DUMMY_VAR__);
      current_statement__ = 19;
      for (int i = 1; i <= Nloc; ++i) {
        current_statement__ = 15;
        stan::model::assign(mu_1,
          (stan::model::rvalue(alpha_gamma, "alpha_gamma",
             stan::model::index_uni(i)) /
          stan::model::rvalue(beta_gamma, "beta_gamma",
            stan::model::index_uni(i))), "assigning variable mu_1",
          stan::model::index_uni(i));
        current_statement__ = 16;
        stan::model::assign(p11,
          (stan::model::rvalue(mu_1, "mu_1", stan::model::index_uni(i)) /
          (stan::model::rvalue(mu_1, "mu_1", stan::model::index_uni(i)) +
          stan::math::exp(beta))), "assigning variable p11",
          stan::model::index_uni(i));
        current_statement__ = 17;
        stan::model::assign(p,
          (stan::model::rvalue(p11, "p11", stan::model::index_uni(i)) +
          stan::math::exp(log_p10)), "assigning variable p",
          stan::model::index_uni(i));
      }
      current_statement__ = 22;
      for (int k = 1; k <= C; ++k) {
        current_statement__ = 20;
        stan::model::assign(coef, (1 +
          stan::math::dot_product(
            stan::model::rvalue(mat, "mat", stan::model::index_uni(k)),
            q_trans)), "assigning variable coef", stan::model::index_uni(k));
      }
      current_statement__ = 25;
      for (int j = 1; j <= C; ++j) {
        current_statement__ = 23;
        stan::model::assign(E_trans,
          (stan::model::rvalue(E, "E", stan::model::index_uni(j)) +
          0.0000000000001), "assigning variable E_trans",
          stan::model::index_uni(j));
      }
      current_statement__ = 6;
      stan::math::check_greater_or_equal(function__, "p11", p11, 0);
      current_statement__ = 6;
      stan::math::check_less_or_equal(function__, "p11", p11, 1);
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "p", p, 0);
      current_statement__ = 7;
      stan::math::check_less_or_equal(function__, "p", p, 1);
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "coef", coef, 0);
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "mu_1", mu_1, 0);
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "E_trans", E_trans, 0);
      {
        current_statement__ = 40;
        for (int j = 1; j <= C; ++j) {
          current_statement__ = 38;
          lp_accum__.add(stan::math::gamma_lpdf<propto__>(
                           stan::model::rvalue(E_trans, "E_trans",
                             stan::model::index_uni(j)),
                           (stan::model::rvalue(coef, "coef",
                              stan::model::index_uni(j)) *
                           stan::model::rvalue(alpha_gamma, "alpha_gamma",
                             stan::model::index_uni(
                               stan::model::rvalue(R, "R",
                                 stan::model::index_uni(j))))),
                           stan::model::rvalue(beta_gamma, "beta_gamma",
                             stan::model::index_uni(
                               stan::model::rvalue(R, "R",
                                 stan::model::index_uni(j))))));
        }
        current_statement__ = 43;
        for (int i = 1; i <= S; ++i) {
          current_statement__ = 41;
          lp_accum__.add(stan::math::binomial_lpmf<propto__>(
                           stan::model::rvalue(K, "K",
                             stan::model::index_uni(i)),
                           stan::model::rvalue(N, "N",
                             stan::model::index_uni(i)),
                           stan::model::rvalue(p, "p",
                             stan::model::index_uni(
                               stan::model::rvalue(L, "L",
                                 stan::model::index_uni(i))))));
        }
        current_statement__ = 44;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(log_p10,
                         stan::model::rvalue(p10priors, "p10priors",
                           stan::model::index_uni(1)),
                         stan::model::rvalue(p10priors, "p10priors",
                           stan::model::index_uni(2))));
        current_statement__ = 45;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta, 0, 10));
        current_statement__ = 46;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(beta_gamma, 0.25,
                         0.25));
        current_statement__ = 47;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(alpha_gamma, 0.01,
                         0.01));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_joint_binary_catchability_gamma_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<double> alpha_gamma =
        std::vector<double>(Nloc, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      alpha_gamma = in__.template read_constrain_lb<
                      std::vector<local_scalar_t__>, jacobian__>(0, lp__,
                      Nloc);
      std::vector<double> beta_gamma =
        std::vector<double>(Nloc, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      beta_gamma = in__.template read_constrain_lb<
                     std::vector<local_scalar_t__>, jacobian__>(0.01, lp__,
                     Nloc);
      double beta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      beta = in__.template read<local_scalar_t__>();
      double log_p10 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      log_p10 = in__.template read_constrain_ub<local_scalar_t__,
                  jacobian__>(0, lp__);
      Eigen::Matrix<double,-1,1> q_trans =
        Eigen::Matrix<double,-1,1>::Constant(nparams,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 5;
      q_trans = in__.template read_constrain_lb<
                  Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(-0.99999,
                  lp__, nparams);
      std::vector<double> p11 =
        std::vector<double>(Nloc, std::numeric_limits<double>::quiet_NaN());
      std::vector<double> p =
        std::vector<double>(Nloc, std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> coef =
        Eigen::Matrix<double,-1,1>::Constant(C,
          std::numeric_limits<double>::quiet_NaN());
      std::vector<double> mu_1 =
        std::vector<double>(Nloc, std::numeric_limits<double>::quiet_NaN());
      std::vector<double> E_trans =
        std::vector<double>(C, std::numeric_limits<double>::quiet_NaN());
      out__.write(alpha_gamma);
      out__.write(beta_gamma);
      out__.write(beta);
      out__.write(log_p10);
      out__.write(q_trans);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 19;
      for (int i = 1; i <= Nloc; ++i) {
        current_statement__ = 15;
        stan::model::assign(mu_1,
          (stan::model::rvalue(alpha_gamma, "alpha_gamma",
             stan::model::index_uni(i)) /
          stan::model::rvalue(beta_gamma, "beta_gamma",
            stan::model::index_uni(i))), "assigning variable mu_1",
          stan::model::index_uni(i));
        current_statement__ = 16;
        stan::model::assign(p11,
          (stan::model::rvalue(mu_1, "mu_1", stan::model::index_uni(i)) /
          (stan::model::rvalue(mu_1, "mu_1", stan::model::index_uni(i)) +
          stan::math::exp(beta))), "assigning variable p11",
          stan::model::index_uni(i));
        current_statement__ = 17;
        stan::model::assign(p,
          (stan::model::rvalue(p11, "p11", stan::model::index_uni(i)) +
          stan::math::exp(log_p10)), "assigning variable p",
          stan::model::index_uni(i));
      }
      current_statement__ = 22;
      for (int k = 1; k <= C; ++k) {
        current_statement__ = 20;
        stan::model::assign(coef, (1 +
          stan::math::dot_product(
            stan::model::rvalue(mat, "mat", stan::model::index_uni(k)),
            q_trans)), "assigning variable coef", stan::model::index_uni(k));
      }
      current_statement__ = 25;
      for (int j = 1; j <= C; ++j) {
        current_statement__ = 23;
        stan::model::assign(E_trans,
          (stan::model::rvalue(E, "E", stan::model::index_uni(j)) +
          0.0000000000001), "assigning variable E_trans",
          stan::model::index_uni(j));
      }
      current_statement__ = 6;
      stan::math::check_greater_or_equal(function__, "p11", p11, 0);
      current_statement__ = 6;
      stan::math::check_less_or_equal(function__, "p11", p11, 1);
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "p", p, 0);
      current_statement__ = 7;
      stan::math::check_less_or_equal(function__, "p", p, 1);
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "coef", coef, 0);
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "mu_1", mu_1, 0);
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "E_trans", E_trans, 0);
      if (emit_transformed_parameters__) {
        out__.write(p11);
        out__.write(p);
        out__.write(coef);
        out__.write(mu_1);
        out__.write(E_trans);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> q =
        Eigen::Matrix<double,-1,1>::Constant(nparams,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> log_lik =
        Eigen::Matrix<double,-1,1>::Constant(log_lik_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> mu =
        Eigen::Matrix<double,-1,-1>::Constant(Nloc, mu_2dim__,
          std::numeric_limits<double>::quiet_NaN());
      double p10 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 26;
      p10 = stan::math::exp(log_p10);
      current_statement__ = 27;
      stan::model::assign(q, stan::math::add(q_trans, 1),
        "assigning variable q");
      current_statement__ = 28;
      stan::model::assign(mu, stan::math::to_vector(mu_1),
        "assigning variable mu", stan::model::index_omni(),
        stan::model::index_uni(1));
      current_statement__ = 31;
      for (int i = 1; i <= nparams; ++i) {
        current_statement__ = 29;
        stan::model::assign(mu,
          stan::math::multiply(stan::math::to_vector(mu_1),
            stan::model::rvalue(q, "q", stan::model::index_uni(i))),
          "assigning variable mu", stan::model::index_omni(),
          stan::model::index_uni((i + 1)));
      }
      current_statement__ = 34;
      for (int j = 1; j <= C; ++j) {
        current_statement__ = 32;
        stan::model::assign(log_lik,
          stan::math::gamma_lpdf<false>(
            stan::model::rvalue(E_trans, "E_trans", stan::model::index_uni(j)),
            (stan::model::rvalue(coef, "coef", stan::model::index_uni(j)) *
            stan::model::rvalue(alpha_gamma, "alpha_gamma",
              stan::model::index_uni(
                stan::model::rvalue(R, "R", stan::model::index_uni(j))))),
            stan::model::rvalue(beta_gamma, "beta_gamma",
              stan::model::index_uni(
                stan::model::rvalue(R, "R", stan::model::index_uni(j))))),
          "assigning variable log_lik", stan::model::index_uni(j));
      }
      current_statement__ = 37;
      for (int i = 1; i <= S; ++i) {
        current_statement__ = 35;
        stan::model::assign(log_lik,
          stan::math::binomial_lpmf<false>(
            stan::model::rvalue(K, "K", stan::model::index_uni(i)),
            stan::model::rvalue(N, "N", stan::model::index_uni(i)),
            stan::model::rvalue(p, "p",
              stan::model::index_uni(
                stan::model::rvalue(L, "L", stan::model::index_uni(i))))),
          "assigning variable log_lik", stan::model::index_uni((C + i)));
      }
      out__.write(q);
      out__.write(log_lik);
      out__.write(mu);
      out__.write(p10);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<local_scalar_t__> alpha_gamma =
        std::vector<local_scalar_t__>(Nloc, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(alpha_gamma,
        in__.read<std::vector<local_scalar_t__>>(Nloc),
        "assigning variable alpha_gamma");
      out__.write_free_lb(0, alpha_gamma);
      std::vector<local_scalar_t__> beta_gamma =
        std::vector<local_scalar_t__>(Nloc, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(beta_gamma,
        in__.read<std::vector<local_scalar_t__>>(Nloc),
        "assigning variable beta_gamma");
      out__.write_free_lb(0.01, beta_gamma);
      local_scalar_t__ beta = DUMMY_VAR__;
      current_statement__ = 3;
      beta = in__.read<local_scalar_t__>();
      out__.write(beta);
      local_scalar_t__ log_p10 = DUMMY_VAR__;
      current_statement__ = 4;
      log_p10 = in__.read<local_scalar_t__>();
      out__.write_free_ub(0, log_p10);
      Eigen::Matrix<local_scalar_t__,-1,1> q_trans =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nparams, DUMMY_VAR__);
      current_statement__ = 5;
      stan::model::assign(q_trans,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(nparams),
        "assigning variable q_trans");
      out__.write_free_lb(-0.99999, q_trans);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "alpha_gamma",
        "double", std::vector<size_t>{static_cast<size_t>(Nloc)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "beta_gamma",
        "double", std::vector<size_t>{static_cast<size_t>(Nloc)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "beta", "double",
        std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "log_p10",
        "double", std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "q_trans",
        "double", std::vector<size_t>{static_cast<size_t>(nparams)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<local_scalar_t__> alpha_gamma =
        std::vector<local_scalar_t__>(Nloc, DUMMY_VAR__);
      current_statement__ = 1;
      alpha_gamma = context__.vals_r("alpha_gamma");
      out__.write_free_lb(0, alpha_gamma);
      std::vector<local_scalar_t__> beta_gamma =
        std::vector<local_scalar_t__>(Nloc, DUMMY_VAR__);
      current_statement__ = 2;
      beta_gamma = context__.vals_r("beta_gamma");
      out__.write_free_lb(0.01, beta_gamma);
      local_scalar_t__ beta = DUMMY_VAR__;
      current_statement__ = 3;
      beta = context__.vals_r("beta")[(1 - 1)];
      out__.write(beta);
      local_scalar_t__ log_p10 = DUMMY_VAR__;
      current_statement__ = 4;
      log_p10 = context__.vals_r("log_p10")[(1 - 1)];
      out__.write_free_ub(0, log_p10);
      Eigen::Matrix<local_scalar_t__,-1,1> q_trans =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nparams, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> q_trans_flat__;
        current_statement__ = 5;
        q_trans_flat__ = context__.vals_r("q_trans");
        current_statement__ = 5;
        pos__ = 1;
        current_statement__ = 5;
        for (int sym1__ = 1; sym1__ <= nparams; ++sym1__) {
          current_statement__ = 5;
          stan::model::assign(q_trans, q_trans_flat__[(pos__ - 1)],
            "assigning variable q_trans", stan::model::index_uni(sym1__));
          current_statement__ = 5;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(-0.99999, q_trans);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"alpha_gamma", "beta_gamma", "beta",
                "log_p10", "q_trans"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"p11", "p", "coef", "mu_1", "E_trans"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"q", "log_lik", "mu", "p10"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    Nloc)},
                std::vector<size_t>{static_cast<size_t>(Nloc)},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(nparams)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(Nloc)},
             std::vector<size_t>{static_cast<size_t>(Nloc)},
             std::vector<size_t>{static_cast<size_t>(C)},
             std::vector<size_t>{static_cast<size_t>(Nloc)},
             std::vector<size_t>{static_cast<size_t>(C)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(nparams)},
             std::vector<size_t>{static_cast<size_t>(log_lik_1dim__)},
             std::vector<size_t>{static_cast<size_t>(Nloc),
               static_cast<size_t>(mu_2dim__)}, std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= Nloc; ++sym1__) {
      param_names__.emplace_back(std::string() + "alpha_gamma" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= Nloc; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta_gamma" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "beta");
    param_names__.emplace_back(std::string() + "log_p10");
    for (int sym1__ = 1; sym1__ <= nparams; ++sym1__) {
      param_names__.emplace_back(std::string() + "q_trans" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= Nloc; ++sym1__) {
        param_names__.emplace_back(std::string() + "p11" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= Nloc; ++sym1__) {
        param_names__.emplace_back(std::string() + "p" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
        param_names__.emplace_back(std::string() + "coef" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= Nloc; ++sym1__) {
        param_names__.emplace_back(std::string() + "mu_1" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
        param_names__.emplace_back(std::string() + "E_trans" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= nparams; ++sym1__) {
        param_names__.emplace_back(std::string() + "q" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= log_lik_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= mu_2dim__; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= Nloc; ++sym2__) {
          param_names__.emplace_back(std::string() + "mu" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      param_names__.emplace_back(std::string() + "p10");
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= Nloc; ++sym1__) {
      param_names__.emplace_back(std::string() + "alpha_gamma" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= Nloc; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta_gamma" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "beta");
    param_names__.emplace_back(std::string() + "log_p10");
    for (int sym1__ = 1; sym1__ <= nparams; ++sym1__) {
      param_names__.emplace_back(std::string() + "q_trans" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= Nloc; ++sym1__) {
        param_names__.emplace_back(std::string() + "p11" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= Nloc; ++sym1__) {
        param_names__.emplace_back(std::string() + "p" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
        param_names__.emplace_back(std::string() + "coef" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= Nloc; ++sym1__) {
        param_names__.emplace_back(std::string() + "mu_1" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
        param_names__.emplace_back(std::string() + "E_trans" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= nparams; ++sym1__) {
        param_names__.emplace_back(std::string() + "q" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= log_lik_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= mu_2dim__; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= Nloc; ++sym2__) {
          param_names__.emplace_back(std::string() + "mu" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      param_names__.emplace_back(std::string() + "p10");
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha_gamma\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nloc) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"beta_gamma\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nloc) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log_p10\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"q_trans\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nparams) + "},\"block\":\"parameters\"},{\"name\":\"p11\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nloc) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"p\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nloc) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"coef\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(C) + "},\"block\":\"transformed_parameters\"},{\"name\":\"mu_1\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nloc) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"E_trans\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(C) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"q\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nparams) + "},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(log_lik_1dim__) + "},\"block\":\"generated_quantities\"},{\"name\":\"mu\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(Nloc) + ",\"cols\":" + std::to_string(mu_2dim__) + "},\"block\":\"generated_quantities\"},{\"name\":\"p10\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha_gamma\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nloc) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"beta_gamma\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nloc) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log_p10\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"q_trans\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nparams) + "},\"block\":\"parameters\"},{\"name\":\"p11\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nloc) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"p\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nloc) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"coef\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(C) + "},\"block\":\"transformed_parameters\"},{\"name\":\"mu_1\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nloc) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"E_trans\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(C) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"q\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nparams) + "},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(log_lik_1dim__) + "},\"block\":\"generated_quantities\"},{\"name\":\"mu\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(Nloc) + ",\"cols\":" + std::to_string(mu_2dim__) + "},\"block\":\"generated_quantities\"},{\"name\":\"p10\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((Nloc + Nloc) + 1) + 1) + nparams);
    const size_t num_transformed = emit_transformed_parameters * (((((Nloc +
      Nloc) + C) + Nloc) + C));
    const size_t num_gen_quantities = emit_generated_quantities * ((((nparams
      + log_lik_1dim__) + (Nloc * mu_2dim__)) + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((Nloc + Nloc) + 1) + 1) + nparams);
    const size_t num_transformed = emit_transformed_parameters * (((((Nloc +
      Nloc) + C) + Nloc) + C));
    const size_t num_gen_quantities = emit_generated_quantities * ((((nparams
      + log_lik_1dim__) + (Nloc * mu_2dim__)) + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_joint_binary_catchability_gamma_namespace::model_joint_binary_catchability_gamma;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_joint_binary_catchability_gamma_namespace::profiles__;
}
#endif
#endif
